### ISSUE TITLE
Support for reindex and scan/scroll queries

### ISSUE THREAD

**Issue by pulkitsinghal** [fullscale/elastic.js#17]
There is currently no way to “update” a mapping in ES … we have to simply rebuild the index. Scan/Scroll allows us to quickly perform a query and iterate over the results. So using scan/scroll over an old index and inserting into a new index is a neat feature.

Here's a link to an example of a Perl client for ES that does this:
https://github.com/clintongormley/ElasticSearch.pm#examples

It would be pretty cool to have something like this in elastic.js for node ... what do you think?

**Comment by mattweber** [comment]
The next version of elastic.js is removing support for low level clients now that the [official javascript client](http://elasticsearch.github.io/elasticsearch-js/index.html) has been released.  Please use the official client since it supports scan/scroll support and the next version of elastic.js will support tight integration with it as well.
