### ISSUE TITLE
Question : How can we get exception when we can't connect to ES Serv

### ISSUE THREAD

**Issue by cmoulliard** [fullscale/elastic.js#32]
Hi,

If the ES server is not responding, then the following exception appears in the javscript console log : "Failed to load resource" 
Is there a way to get this info from ejs.Request() ?

Regards,

Charles

**Comment by porjo** [comment]
I was wondering the same thing. 

When my ES server is down I get this error in my console log:
 `SyntaxError: JSON.parse: unexpected end of data @ http://code.jquery.com/jquery-1.9.1.min.js:3` 

I'm passing an error callback to [`Request.doSearch()`](http://docs.fullscale.co/elasticjs/ejs.Request.html#ejs.Request.doSearch) and I'm also catching Ajax errors with [Jquery `ajaxError()`](http://api.jquery.com/ajaxError/), however neither of these get called in this instance.

**Comment by svperfecta** [comment]
I just ran into the same error.  Essentially, if the server goes offline after I've already setup my client, no error gets thrown, no error callbacks are called.

**Comment by svperfecta** [comment]
Note: On the plus side, it seems to reconnect quite well!

**Comment by mattweber** [comment]
I will look into this.  Is this with the jquery client only?

**Comment by brubrant** [comment]
I think it affects node as well. If I lose connection to elasticseach my app/server crashes.

**Comment by mattweber** [comment]
Low level client support is being removed due to the release of the [official javascript client](http://elasticsearch.github.io/elasticsearch-js/index.html).  The next version of elastic.js will provide full integration with the official client.  The official client support node, angular, and jquery clients as well, so please investigate using that with the master version of elastic.js.
