### ISSUE TITLE
Angular Version Compatibility

### ISSUE THREAD

**Issue by chrismacp** [fullscale/elastic.js#46]
Hi,

It would be useful if you had some information about compatibility with angular versions.

I just spent a while trying to work out why my code wouldn't work, the response of a query was missing the data in the response object. It seemed that I had too new a version of Angular as I was using the latest 1.2.3. I downgraded to 1.0.8 and it worked fine.

Just thought that might help some others. 

Loving your work though :)

Chris

**Comment by michael-bouvy** [comment]
Hi Chris,

I also couldn't get the provided examples with Angular.JS 1.2.x, and finally figured out it was due to fact that templates do not anymore automatically unwrap Promises (see http://docs.angularjs.org/guide/migration#templates-no-longer-automatically-unwrap-promises).

You may unwrap the returned Promise by calling it's method "then" with a callback as sole argument : 

``` javascript
var promise = request
    .query(ejs.QueryStringQuery($scope.queryTerm || '*'))
    .doSearch();

promise.then(function (data) {
    $scope.results = data;
});
```

By the way, as ngRoute is now a standalone module, you should include the JS in your code and require the module in your Angular.JS app declaration within `examples/angular/js/app.js`.

Hope that helps :)

**Comment by chrismacp** [comment]
Hey,

Thanks for explaining that, and for the link to the Angular docs. I'm pretty new to the subject and hadn't really used promises at that point so didn't recognise the 'then' function name in the response as being something relevant. 

Makes complete sense now and so I've upgraded my Angular version again with success.

Cheers,

Chris
